### PR TITLE
Change update functions & readme

### LINKED ISSUE #85: Cannot get corpus dir
According to the README, I can get the corpus dir. But when I run the recommended command, I get an error

```
λ python -c "from allofplos.plos_regex import corpusdir; print(corpusdir)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'corpusdir'
```

Environment:

```
λ python --version
Python 3.5.2
λ pip freeze
allofplos==0.10.2
certifi==2018.1.18
chardet==3.0.4
idna==2.6
lxml==4.1.1
peewee==3.1.0
pkg-resources==0.0.0
python-utils==2.3.0
requests==2.18.4
six==1.11.0
tqdm==4.19.5
Unidecode==1.0.22
urllib3==1.22
```

### PR DESCRIPTION
**Pull request by eseiver**
This closes #85.
- deprecates `allofplos.plos_corpus` in favor of `allofplos.update`
- updates README with new command (as well as other readme cleanup)
- `filename_to_doi` no longer allows passing through a DOI (it was broken by #87, oops)
- new `download_xml` function is based on DOI and not file, and is passed into `download_updated_xml`.

### CODE REVIEW

File: allofplos/update.py [hunk 1]
```diff
@@ -0,0 +1,4 @@
+from .corpus.plos_corpus import main
```
Comment (mpacer) [inline allofplos/update.py]: If we're going to do this, I'd prefer that the meat of this functionality actually be moved into this file and rely on the `corpus` module to provide the actual APIs it uses internally. This kind of redirection is getting to be a bit gratuitous. But if this would include a true refactor (making `python -m allofplos.corpus.plos_corpus` invalid, then I'd be for this.

Comment (mpacer) [reply allofplos/update.py]: I'll note that I've been trying to push us to have a deeper package structure, and so introducing another top level module isn't exactly a great idea in my opinion. 

However, I think it's important to separate the applications from the APIs, and this is effectively an application style command, so that's why I'm in favour of adding this at the cost of a flatter package structure to gain the isolation of purpose.

File: allofplos/transformations.py [hunk 2]
```diff
@@ -94,15 +94,14 @@ def filename_to_doi(filename):
     :param filename: relative path to local XML file in the get_corpus_dir() directory
     :return: full unique identifier for a PLOS article
     """
-    filename = os.path.basename(filename)
-    if correction in filename and validate_filename(filename):
+    fn = os.path.basename(filename)
```
Comment (mpacer) [inline allofplos/transformations.py]: couldn't you change the `filename`parameter to `filepath` and then keep this as `filename`?

I always feel conflicted about `fn` since it can also be shorthand for `function`, especially in callback based code.

File: allofplos/plos_corpus.py [hunk 3]
```diff
@@ -1,4 +1,10 @@
+import warnings
+
 from .corpus.plos_corpus import main
 
 if __name__ == "__main__":
+    warnings.simplefilter('always', DeprecationWarning)
+    warnings.warn("This update method is deprecated. use 'python -m allofplos.update'",
```
Comment (mpacer) [inline allofplos/plos_corpus.py]: Yay deprecation warnings!

File: allofplos/corpus/plos_corpus.py [hunk 4]
```diff
@@ -278,9 +278,16 @@ def compare_article_pubdate(doi, days=22, directory=None):
         print("Pubdate error in {}".format(doi))
 
 
+def download_xml(doi, tempdir=newarticledir):
```
Comment (mpacer) [inline allofplos/corpus/plos_corpus.py]: That is really clever! I hadn't thought of using an article object as a downloader… why don't we just bake this into the article class itself?

File: allofplos/transformations.py [hunk 5]
```diff
@@ -100,9 +100,8 @@ def filename_to_doi(filename):
         doi = PREFIX + article
     elif validate_filename(filename):
         doi = PREFIX + os.path.splitext(filename)[0]
-    # NOTE: A filename should never validate as a DOI, so the next elif is wrong.
-    elif validate_doi(filename):
-        doi = filename
+    else:
+        doi = ''
     return doi
```
Comment (mpacer) [inline allofplos/transformations.py]: You should validate the doi before returning it.

File: allofplos/corpus/plos_corpus.py [hunk 6]
```diff
@@ -496,10 +491,10 @@ def download_vor_updates(directory=None, tempdir=newarticledir,
     if vor_updates_available is None:
         vor_updates_available = check_for_vor_updates()
     vor_updated_article_list = []
-    for article in tqdm(vor_updates_available, disable=None):
-        updated = download_updated_xml(article, vor_check=True)
+    for doi in tqdm(vor_updates_available, disable=None):
```
Comment (mpacer) [inline allofplos/corpus/plos_corpus.py]: Does vor_updates_available return a list of dois?

File: allofplos/transformations.py (hunk 5 above)
Comment (mpacer) [reply allofplos/transformations.py]: Do we have a custom doi validation error? If not… we should.

Comment (mpacer) [reply allofplos/transformations.py]: BTW, you have the same problem with doi_to_path

https://github.com/PLOS/allofplos/pull/88/files?diff=unified#diff-ad065d41199b64627a6f15ef79720843R181

```
     if directory is None:
         directory = get_corpus_dir()
     if doi.startswith(ANNOTATION_DOI) and validate_doi(doi):
         article_file = os.path.join(directory, "plos.correction." + doi.split('/')[-1] + SUFFIX_LOWER)
     elif validate_doi(doi):
         article_file = os.path.join(directory, doi.lstrip(PREFIX) + SUFFIX_LOWER)
     # NOTE: The following check is weird, a DOI should never validate as a file name.
     elif validate_filename(doi):
         article_file = doi
     return article_file
```

it should have an else case.

File: README.rst [hunk 7]
```diff
@@ -106,9 +106,9 @@ Should return something like this:
 
 ::
 
-      ......
+      ........
       ----------------------------------------------------------------------
-      Ran 6 tests in 3.327s
+      Ran 8 tests in 0.257s
```
Comment (mpacer) [inline README.rst]: This is no longer accurate after #89, could you update it?

File: allofplos/update.py [hunk 8]
```diff
@@ -0,0 +1,52 @@
+import os
+
+from . import get_corpus_dir, newarticledir, uncorrected_proofs_text_list
```
Comment (mpacer) [inline allofplos/update.py]: I don't think this will work anymore, you'll need to get those from .corpus, right?

Comment (mpacer) [inline allofplos/update.py]: Why is uncorrect_proofs_text_list in __init__.py? Isn't it specific to the update function? Does anything else use it?

**Comment by mpacer** [comment]
There is now an issue with our entrypoints… I actually didn't know we had a console_script entrypoint. but you'll want to change that too… or remove it, because I don't know if it works right now.

File: allofplos/transformations.py [hunk 9]
```diff
@@ -100,9 +100,8 @@ def filename_to_doi(filename):
         doi = PREFIX + article
     elif validate_filename(filename):
         doi = PREFIX + os.path.splitext(filename)[0]
-    # NOTE: A filename should never validate as a DOI, so the next elif is wrong.
-    elif validate_doi(filename):
-        doi = filename
+    else:
+        raise Exception("Invalid format for PLOS filename: {}".format(filename))
```
Comment (mpacer) [inline allofplos/transformations.py]: could you add the same validate_filename check at the beginning of the of this functiont hat you did below for the `doi_to_url` check? that way you could remove all of the other calls to validate filename later on and simplify the logic.

File: allofplos/update.py (hunk 8 above)
Comment (eseiver) [reply allofplos/update.py]: because the .txt file is stored in the top-level directory (which made sense when `plos_corpus.py` was there).

File: allofplos/transformations.py [hunk 10]
```diff
@@ -178,9 +179,8 @@ def doi_to_path(doi, directory=None):
         article_file = os.path.join(directory, "plos.correction." + doi.split('/')[-1] + SUFFIX_LOWER)
     elif validate_doi(doi):
         article_file = os.path.join(directory, doi.lstrip(PREFIX) + SUFFIX_LOWER)
-    # NOTE: The following check is weird, a DOI should never validate as a file name.
-    elif validate_filename(doi):
-        article_file = doi
+    else:
```
Comment (mpacer) [inline allofplos/transformations.py]: I really like the way you simplified the check with validate doi in `filename_to_doi`, could you use that method here as well? Checking for validation first that way you don't need to keep adding it as part of your conditions?

File: allofplos/update.py (hunk 8 above)
Comment (mpacer) [reply allofplos/update.py]: It will be wiped out when you reinstall allofplos

Comment (eseiver) [reply allofplos/update.py]: yes, just like people who have installed the corpus directory in the default location. let's make obsolete in future PR

**Comment by mpacer** [comment]
LGTM, merging
